---
- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart Docker firewall
  ansible.builtin.systemd_service:
    name: loresuelvo-docker-firewall.service
    enabled: true
    state: restarted
