API_SERVER_NAMES=api-test.loresuelvo.com.ar
WEB_SERVER_NAMES=test.loresuelvo.com.ar
ADMIN_SERVER_NAMES=gestion-test.loresuelvo.com.ar
ANDROID_APP_LINK_PACKAGE_NAME=com.loresuelvo.consumer.staging
ANDROID_APP_LINK_SHA256_CERT_FINGERPRINT=00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
