API_SERVER_NAMES=api-test.loresuelvo.com.ar
WEB_SERVER_NAMES=test.loresuelvo.com.ar
ADMIN_SERVER_NAMES=gestion-test.loresuelvo.com.ar
ANDROID_APP_LINK_PACKAGE_NAME=com.loresuelvo.consumer.staging
ANDROID_APP_LINK_SHA256_CERT_FINGERPRINT=10:F5:32:D3:22:40:BC:6D:E5:72:73:92:27:8E:E3:A7:22:73:47:9F:57:0E:94:45:04:AA:29:E7:09:17:D5:1A
