name: Test Infisical

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  test-infisical:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch API staging secrets
        uses: Infisical/secrets-action@v1.0.16
        with:
          method: "oidc"
          identity-id: "TU_MACHINE_IDENTITY_ID"
          project-slug: "TU_PROJECT_SLUG"
          env-slug: "staging"
          secret-path: "/api"

      - name: Verify secrets
        run: |
          if [ -z "$DATABASE_URL" ]; then
            echo "DATABASE_URL no fue cargada"
            exit 1
          fi

          echo "Infisical API staging OK"