name: Scale UP

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      terraform-root:
        type: string
        required: true
      desired-replica-count:
        type: number
        required: true
      current-replica-count:
        type: string
        required: true

permissions:
  contents: read
  id-token: write
  deployments: read

jobs:
  create:
    name: Create new VMs
    uses: ./.github/workflows/replica-apply.yml
    with:
      environment: ${{ inputs.environment }}
      terraform-root: ${{ inputs.terraform-root }}
      desired-replica-count: ${{ inputs.desired-replica-count }}
      expected-current-count: ${{ inputs.current-replica-count }}
    secrets: inherit

  configure:
    name: Configure new VMs
    needs: create
    uses: ./.github/workflows/replica-configure.yml
    with:
      environment: ${{ inputs.environment }}
      terraform-root: ${{ inputs.terraform-root }}
      desired-replica-count: ${{ inputs.desired-replica-count }}
      previous-replica-count: ${{ inputs.current-replica-count }}
    secrets: inherit

  deploy:
    name: Deploy applications and gateway
    needs: configure
    uses: ./.github/workflows/replica-deploy.yml
    with:
      environment: ${{ inputs.environment }}
      terraform-root: ${{ inputs.terraform-root }}
      desired-replica-count: ${{ inputs.desired-replica-count }}
      previous-replica-count: ${{ inputs.current-replica-count }}
    secrets: inherit

  verify:
    name: Verify deployments locally
    needs: deploy
    uses: ./.github/workflows/replica-verify.yml
    with:
      environment: ${{ inputs.environment }}
      terraform-root: ${{ inputs.terraform-root }}
    secrets: inherit

  activate:
    name: Add verified origins to Cloudflare
    needs: verify
    uses: ./.github/workflows/sync-load-balancer.yml
    with:
      environment: ${{ inputs.environment }}
      replicas-terraform-root: ${{ inputs.terraform-root }}
      active-replica-count: ${{ inputs.desired-replica-count }}
      mode: activate
    secrets: inherit
